trigger:
  - "*"

variables:
  buildConfiguration: "Debug"
  outputDirectory: "$(build.binariesDirectory)/$(buildConfiguration)"

pool:
  vmImage: macos-latest

steps:
  - task: NuGetCommand@2
    inputs:
      restoreSolution: "**/*.sln"

  - task: XamarinAndroid@1
    inputs:
      projectFile: "**/*droid*.csproj"
      outputDirectory: "$(outputDirectory)"
      configuration: "$(buildConfiguration)"

  - task: AndroidSigning@3
    inputs:
      apkFiles: "$(outputDirectory)/*.apk"
      apksignerKeystoreFile: "Bitspace.keystore"
      apksignerKeystorePassword: "$(KEYSTOREPASSWORD)"
      apksignerKeystoreAlias: "Bitspace"
      zipalign: true
      

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: "App Center Connection"
      appSlug: "drtardis1/Bitspace"
      appFile: "$(outputDirectory)/*.apk"
      symbolsOption: "Android"
      releaseNotesOption: input
      releaseNotesInput: "Release notes would go here, if there were any!"
      destinationType: "groups"