//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitspace.Resources.Copy {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bitspace_Global {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Bitspace_Global() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bitspace.Resources.Registers.Copy.Bitspace", typeof(Bitspace_Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NAV_CLOSE {
            get {
                return ResourceManager.GetString("NAV_CLOSE", resourceCulture);
            }
        }
        
        public static string NAV_BACK {
            get {
                return ResourceManager.GetString("NAV_BACK", resourceCulture);
            }
        }
        
        public static string NAV_CANCEL {
            get {
                return ResourceManager.GetString("NAV_CANCEL", resourceCulture);
            }
        }
        
        public static string NAV_DONE {
            get {
                return ResourceManager.GetString("NAV_DONE", resourceCulture);
            }
        }
        
        public static string NAV_NEXT {
            get {
                return ResourceManager.GetString("NAV_NEXT", resourceCulture);
            }
        }
    }
}
