//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitspace.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConnectFourRegister {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ConnectFourRegister() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitspace.Resources.Registers.Copy.ConnectFourRegister", typeof(ConnectFourRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} is out of range {1} - {2}..
        /// </summary>
        public static string CF_COL_EX {
            get {
                return ResourceManager.GetString("CF_COL_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string CF_CONGRATS {
            get {
                return ResourceManager.GetString("CF_CONGRATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is thinking....
        /// </summary>
        public static string CF_ENGINE_BUSY {
            get {
                return ResourceManager.GetString("CF_ENGINE_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is waiting....
        /// </summary>
        public static string CF_ENGINE_IDLE {
            get {
                return ResourceManager.GetString("CF_ENGINE_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martini.
        /// </summary>
        public static string CF_ENGINE_NAME {
            get {
                return ResourceManager.GetString("CF_ENGINE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string CF_NEW_GAME {
            get {
                return ResourceManager.GetString("CF_NEW_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play again?.
        /// </summary>
        public static string CF_PLAY_AGAIN {
            get {
                return ResourceManager.GetString("CF_PLAY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}.
        /// </summary>
        public static string CF_PLAYER {
            get {
                return ResourceManager.GetString("CF_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string CF_QUIT {
            get {
                return ResourceManager.GetString("CF_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations {0}, you won!.
        /// </summary>
        public static string CF_WIN {
            get {
                return ResourceManager.GetString("CF_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the winner!.
        /// </summary>
        public static string CF_WINNER {
            get {
                return ResourceManager.GetString("CF_WINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Four Page.
        /// </summary>
        public static string PAGE_NAME {
            get {
                return ResourceManager.GetString("PAGE_NAME", resourceCulture);
            }
        }
    }
}
