//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitspace.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageRegister {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageRegister() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bitspace.Resources.Registers.Copy.HomePageRegister", typeof(HomePageRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WEATHER_FORECAST_TITLE {
            get {
                return ResourceManager.GetString("WEATHER_FORECAST_TITLE", resourceCulture);
            }
        }
        
        internal static string WELCOME_TO {
            get {
                return ResourceManager.GetString("WELCOME_TO", resourceCulture);
            }
        }
        
        internal static string BITSPACE {
            get {
                return ResourceManager.GetString("BITSPACE", resourceCulture);
            }
        }
        
        internal static string QR_CODE_SCANNER_TITLE {
            get {
                return ResourceManager.GetString("QR_CODE_SCANNER_TITLE", resourceCulture);
            }
        }
        
        internal static string MARTINI {
            get {
                return ResourceManager.GetString("MARTINI", resourceCulture);
            }
        }
        
        internal static string PAGE_NAME {
            get {
                return ResourceManager.GetString("PAGE_NAME", resourceCulture);
            }
        }
    }
}
