//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitspace.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WeatherForecastPageRegister {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherForecastPageRegister() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bitspace.Resources.Registers.Copy.WeatherForecastPageRegister", typeof(WeatherForecastPageRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HUMIDITY {
            get {
                return ResourceManager.GetString("HUMIDITY", resourceCulture);
            }
        }
        
        internal static string WIND_SPEED {
            get {
                return ResourceManager.GetString("WIND_SPEED", resourceCulture);
            }
        }
        
        internal static string UVIndex {
            get {
                return ResourceManager.GetString("UVIndex", resourceCulture);
            }
        }
        
        internal static string PRESSURE {
            get {
                return ResourceManager.GetString("PRESSURE", resourceCulture);
            }
        }
        
        internal static string PAGE_NAME {
            get {
                return ResourceManager.GetString("PAGE_NAME", resourceCulture);
            }
        }
    }
}
