//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitspace.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConnectFourRegister {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ConnectFourRegister() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bitspace.Resources.Registers.ConnectFourRegister", typeof(ConnectFourRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CF_COL_EX {
            get {
                return ResourceManager.GetString("CF_COL_EX", resourceCulture);
            }
        }
        
        public static string CF_WIN {
            get {
                return ResourceManager.GetString("CF_WIN", resourceCulture);
            }
        }
        
        public static string CF_CONGRATS {
            get {
                return ResourceManager.GetString("CF_CONGRATS", resourceCulture);
            }
        }
        
        public static string CF_WINNER {
            get {
                return ResourceManager.GetString("CF_WINNER", resourceCulture);
            }
        }
        
        public static string CF_PLAY_AGAIN {
            get {
                return ResourceManager.GetString("CF_PLAY_AGAIN", resourceCulture);
            }
        }
        
        public static string CF_NEW_GAME {
            get {
                return ResourceManager.GetString("CF_NEW_GAME", resourceCulture);
            }
        }
        
        public static string CF_QUIT {
            get {
                return ResourceManager.GetString("CF_QUIT", resourceCulture);
            }
        }
    }
}
